version: '3'
services:
  web:
    build: .
    ports:
      - "80:80"
    links:
      - database
    volumes:
      - ./www:/var/www/dembelo/www
      - ./scripts:/var/www/dembelo/scripts
      - ./docker/scripts:/var/www/dembelo/docker/scripts
    environment:
      PHP_IDE_CONFIG: "serverName=Docker"
  database:
    image: "mongo"
    ports:
      - "27017:27017"
    volumes:
      - ./docker/mongodb_data:/data/db