imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: de
    topic_image_directory: '%kernel.root_dir%/../uploads/topicimage/'
    twine_directory: '%kernel.root_dir%/../uploads/twine/'

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true
    assets: ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form_themes: ['bootstrap_3_layout.html.twig']
    globals:
        piwik_host: "%piwik_host%"
        piwik_id: "%piwik_id%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ DembeloMain, AdminBundle ]
    #java: /usr/bin/java
    sass:           /usr/local/bin/sass
    filters:
        cssrewrite: ~
        sass: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"
    assets:
        glyphicons-halflings-regular-woff:
            inputs: '%kernel.root_dir%/../vendor/twbs/bootstrap-sass/assets/fonts/bootstrap/glyphicons-halflings-regular.woff'
            output: 'css/fonts/bootstrap/glyphicons-halflings-regular.woff'
        glyphicons-halflings-regular-woff2:
            inputs: '%kernel.root_dir%/../vendor/twbs/bootstrap-sass/assets/fonts/bootstrap/glyphicons-halflings-regular.woff2'
            output: 'css/fonts/bootstrap/glyphicons-halflings-regular.woff2'
        glyphicons-halflings-regular-ttf:
            inputs: '%kernel.root_dir%/../vendor/twbs/bootstrap-sass/assets/fonts/bootstrap/glyphicons-halflings-regular.ttf'
            output: 'css/fonts/bootstrap/glyphicons-halflings-regular.ttf'
        linlibertine-regular-woff:
            inputs: '@DembeloMain/Resources/public/fonts/LinLibertine/LinLibertine_R.woff'
            output: 'css/fonts/linlibertine/LinLibertine_R.woff'
        linlibertine-regular-otf:
            inputs: '@DembeloMain/Resources/public/fonts/LinLibertine/LinLibertine_R.otf'
            output: 'css/fonts/linlibertine/LinLibertine_R.otf'
        linlibertine-regular-svg:
            inputs: '@DembeloMain/Resources/public/fonts/LinLibertine/LinLibertine_R.svg'
            output: 'css/fonts/linlibertine/LinLibertine_R.svg'
        linlibertine-regular-ttf:
            inputs: '@DembeloMain/Resources/public/fonts/LinLibertine/LinLibertine_Rah.ttf'
            output: 'css/fonts/linlibertine/LinLibertine_Rah.ttf'
        requirejs:
            inputs: '%kernel.root_dir%/../vendor/etdsolutions/requirejs/require.js'
            output: 'js/libs/require.js'

# Doctrine Configuration
doctrine_mongodb:
    connections:
        default:
            server: mongodb://localhost:27017
            options: {}
    default_database: dembelo
    document_managers:
        default:
            auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }
