imports:
    - { resource: config_dev.yml }

doctrine_mongodb:
    default_database: dembelo_test

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

security:
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js|install|admin)/
            security: false
