app:
    resource: "@DembeloMain/Controller/"
    type:     annotation

admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation
    prefix:   /admin

logout:
    path: /logout

mainpage:
    path:     /
    defaults: { _controller: app.controller_dashboard:indexAction }