app:
    resource: "@DembeloMain/Controller/"
    type:     annotation

admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation
    prefix:   /admin

admin_topic:
    path:     /admin/topic
    defaults: { _controller: app.controller_admin_topic.listAction }

logout:
    path: /logout

mainpage:
    path:     /
    defaults: { _controller: app.controller_dashboard:indexAction }