# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    admin.import.twine:
        class: AdminBundle\Model\ImportTwine
        arguments:
            - "@app.twineImport.fileextractor"
            - "@app.twineImport.filecheck"
            - "@app.twineImport.storyDataParser"
            - "@app.twineImport.passageDataParser"
            - "@app.twineImport.parserContext"

    # @todo remove dependency from service container
    app.feature_toggle:
        class: DembeloMain\Model\FeatureToggle
        calls:
        - [setContainer, ["@service_container"]]

    app.readpath:
        class: DembeloMain\Model\Readpath
        arguments: ["@app.model_repository_read_path", "@session"]

    app.controller_dashboard:
        class: DembeloMain\Controller\Dashboard\DefaultController
        calls:
            - [setContainer, ["@service_container"]]

    app.controller_default:
        class: DembeloMain\Controller\DefaultController
        arguments:
            - "@app.feature_toggle"
            - "@security.authorization_checker"
            - "@app.model_repository_user"
            - "@app.model_repository_textnode"
            - "@templating"
            - "@router"
            - "@security.token_storage"
            - "@app.readpath"
            - "@app.favoriteManager"
            - "@app.readpathUndoService"
        class:
            - [setContainer, ["@service_container"]]

    app.admin_controller_default:
        class: AdminBundle\Controller\DefaultController
        arguments:
            - "@templating"
            - "@app.model_repository_user"
            - "@app.model_repository_licensee"
            - "@app.model_repository_topic"
            - "@app.model_repository_importfile"
            - "@security.password_encoder"
            - %twine_directory%
            - %topic_image_directory%
            - "@filesystem"

    app.admin_controller_user:
        class: AdminBundle\Controller\UserController
        arguments:
            - "@app.model_repository_user"
            - "@mailer"

    app.admin_controller_licensee:
            class: AdminBundle\Controller\LicenseeController
            arguments:
                - "@app.model_repository_licensee"

    app.admin_controller_textnode:
            class: AdminBundle\Controller\TextnodeController
            arguments:
                - "@app.model_repository_textnode"
                - "@app.model_repository_importfile"
                - "@app.model_repository_licensee"

    app.admin_controller_importfile:
        class: AdminBundle\Controller\ImportfileController
        arguments:
            - "@app.model_repository_importfile"
            - "@admin.import.twine"
            - "@doctrine_mongodb"
            - %twine_directory%

    app.controller_admin_topic:
        class: AdminBundle\Controller\TopicController
        arguments: ["@app.model_repository_topic"]

    app.model_repository_topic:
        class: DembeloMain\Model\Repository\Doctrine\ODM\TopicRepository
        factory: ["@doctrine_mongodb.odm.document_manager", getRepository]
        arguments:
            - DembeloMain\Document\Topic

    app.model_repository_textnode:
        class: DembeloMain\Model\Repository\Doctrine\ODM\TextNodeRepository
        factory: ["@doctrine_mongodb.odm.document_manager", getRepository]
        arguments:
            - DembeloMain\Document\Textnode

    app.model_repository_read_path:
        class: DembeloMain\Model\Repository\Doctrine\ODM\ReadPathRepository
        factory: ["@doctrine_mongodb.odm.document_manager", getRepository]
        arguments:
            - DembeloMain\Document\Readpath

    app.model_repository_licensee:
        class: DembeloMain\Model\Repository\Doctrine\ODM\LicenseeRepository
        factory: ["@doctrine_mongodb.odm.document_manager", getRepository]
        arguments:
            - DembeloMain\Document\Licensee

    app.model_repository_user:
        class: DembeloMain\Model\Repository\Doctrine\ODM\UserRepository
        factory: ["@doctrine_mongodb.odm.document_manager", getRepository]
        arguments:
            - DembeloMain\Document\User

    app.model_repository_importfile:
            class: DembeloMain\Model\Repository\Doctrine\ODM\ImportfileRepository
            factory: ["@doctrine_mongodb.odm.document_manager", getRepository]
            arguments:
                - DembeloMain\Document\Importfile

    # @todo remove dependency from service container
    app.twig_extension.version:
            class: DembeloMain\Twig\VersionExtension
            arguments: ["@service_container"]
            public: false
            tags:
                - { name: twig.extension }

    # @todo remove dependency from service container
    app.twig_extension.hasFeature:
                class: DembeloMain\Twig\FeatureToggleExtension
                arguments: ["@service_container"]
                public: false
                tags:
                    - { name: twig.extension }

    app.requestlistener_session_expiration:
            class: DembeloMain\EventListener\RequestListener
            tags:
                - { name: kernel.event_listener, event: kernel.request, method: onRequest }

    app.favoriteManager:
            class: DembeloMain\Model\FavoriteManager
            arguments: ["@session"]

    app.readpathUndoService:
                class: DembeloMain\Service\ReadpathUndoService
                arguments: ["@session"]

    app.twineImport.hitchparser:
            class: AdminBundle\Service\TwineImport\HitchParser
            arguments: ["@app.model_repository_textnode"]

    app.twineImport.fileextractor:
            class: AdminBundle\Service\TwineImport\FileExtractor

    app.twineImport.filecheck:
            class: AdminBundle\Service\TwineImport\FileCheck

    app.twineImport.storyDataParser:
        class: AdminBundle\Service\TwineImport\StoryDataParser
        arguments:
            - "@app.twineImport.hitchparser"
            - "@app.model_repository_textnode"

    app.twineImport.passageDataParser:
        class: AdminBundle\Service\TwineImport\PassageDataParser
        arguments:
            - "@app.model_repository_textnode"

    app.twineImport.parserContext:
        class: AdminBundle\Service\TwineImport\ParserContext