# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    admin.import.twine:
        class: AdminBundle\Model\ImportTwine
        arguments: ["@app.model_repository_textNode", "@app.model_repository_topic"]
#    service_name:
#        class: DembeloMain\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    app.feature_toggle:
        class: DembeloMain\Model\FeatureToggle
        calls:
        - [setContainer, ["@service_container"]]

    app.readpath:
        class: DembeloMain\Model\Readpath
        arguments: ["@app.model_repository_read_path", "@session"]

    app.controller_dashboard:
        class: DembeloMain\Controller\Dashboard\DefaultController
        calls:
                - [setContainer, ["@service_container"]]

    app.controller_admin_topic:
        class: AdminBundle\Controller\TopicController
        arguments: ["@service_container", "@app.model_repository_topic"]

    app.model_repository_topic:
        class: DembeloMain\Model\Repository\Doctrine\ODM\TopicRepository
        factory: ["@doctrine_mongodb.odm.document_manager", getRepository]
        arguments:
            - DembeloMain\Document\Topic

    app.model_repository_textNode:
        class: DembeloMain\Model\Repository\Doctrine\ODM\TextNodeRepository
        factory: ["@doctrine_mongodb.odm.document_manager", getRepository]
        arguments:
            - DembeloMain\Document\Textnode

    app.model_repository_read_path:
        class: DembeloMain\Model\Repository\Doctrine\ODM\ReadPathRepository
        factory: ["@doctrine_mongodb.odm.document_manager", getRepository]
        arguments:
            - DembeloMain\Document\Readpath

    app.model_repository_licensee:
        class: DembeloMain\Model\Repository\Doctrine\ODM\LicenseeRepository
        factory: ["@doctrine_mongodb.odm.document_manager", getRepository]
        arguments:
            - DembeloMain\Document\Licensee

    app.model_repository_user:
        class: DembeloMain\Model\Repository\Doctrine\ODM\UserRepository
        factory: ["@doctrine_mongodb.odm.document_manager", getRepository]
        arguments:
            - DembeloMain\Document\User

    app.model_repository_importfile:
            class: DembeloMain\Model\Repository\Doctrine\ODM\ImportfileRepository
            factory: ["@doctrine_mongodb.odm.document_manager", getRepository]
            arguments:
                - DembeloMain\Document\Importfile

    app.twig_extension.version:
            class: DembeloMain\Twig\VersionExtension
            arguments: ["@service_container"]
            public: false
            tags:
                - { name: twig.extension }

    app.twig_extension.hasFeature:
                class: DembeloMain\Twig\FeatureToggleExtension
                arguments: ["@service_container"]
                public: false
                tags:
                    - { name: twig.extension }

    app.requestlistener_session_expiration:
            class: DembeloMain\EventListener\RequestListener
            tags:
                - { name: kernel.event_listener, event: kernel.request, method: onRequest }

    app.favoriteManager:
            class: DembeloMain\Model\FavoriteManager
            arguments: ["@session"]